# Generated by Django 3.0.5 on 2020-04-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
