# Generated by Django 3.0.5 on 2020-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_source',
            field=models.CharField(default='', max_length=400),
        ),
    ]
