# Generated by Django 3.0.5 on 2020-06-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_auto_20200506_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_embed',
            field=models.CharField(default='', max_length=400),
        ),
    ]
